### ISSUE TITLE
Tracing events

### ISSUE THREAD

**Issue by hauleth** [beam-telemetry/telemetry#25] opened 2018-12-15 20:24 UTC
It would be great to have built-in support for tracing events along metrics. It would provide nice API to digest by OpenCensus, Spandex, and possibly other tracers out there. While this can be currently "improvised" via creating events in form of `[:event, :start]` and `[:event, :end]` there are few problems with that approach:

- it is hard to match `:start` with it's `:end`
- it requires "best common practices" instead of forcing nomenclature on everyone

**Comment by josevalim** [comment] 2018-12-15 20:34
This is somewhat a duplicate of #24. It is something we want to tackle but
our priority is to get the minimal that we have now out, then we can focus
on tracing. We are also considering maybe using Erlang’s logger for the
tracing. We don’t know yet (which is why this isn’t our focus). :)
-- 


*José Valim*
www.plataformatec.com.br
Skype: jv.ptec
Founder and Director of R&D

**Closed** 2018-12-15 20:58 UTC

**Comment by hauleth** [comment] 2018-12-15 22:41
Worth mentioning that tracing via Erlang's logger is already done, at least for OpenCensus https://github.com/ferd/tracelog
